name: Update README with Blog Posts

on:
  schedule:
    - cron: '0 * * * *'   # runs every hour
  workflow_dispatch:       # allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull RSS feed and update README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://trankhanh0605.wordpress.com/feed/"
          max_post_count: 15
